services:
  backend:
    image: amankhan1009/file-assistant-backend:latest

    env_file:
      - .env

    environment:
      WORKSPACE_ROOT: workspace

    ports:
      - "8000:8000"

    volumes:
      - file_assistant_workspace:/app/workspace
      - file_assistant_database:/app/database
      - file_assistant_logs:/app/logs

    restart: unless-stopped

  frontend:
    image: amankhan1009/file-assistant-frontend:latest

    environment:
      FILE_ASSISTANT_API_URL: http://backend:8000

    ports:
      - "8501:8501"

    depends_on:
      - backend

    restart: unless-stopped


volumes:
  file_assistant_workspace:
  file_assistant_database:
  file_assistant_logs:
